### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#37]
This is a tracking issue for issues that need to be closed for the 1.0 release of straight.el:

* [ ] Improve user experience around package building:
    * [x] Fix slowness while reloading init-file (#35).
    * [x] Fix duplicate warnings on changing recipe (#34).
    * [x] Investigate whether packages are built more than once during
      init (#27).
    * [x] Add straight-rebuild and straight-rebuild-all commands (#10).
    * [x] Dependencies are screwed up when installing after init.
    * [x] Install even built-in packages (#38).
    * [ ] Record individual packages in bulk find(1) operation (#42).
    * [ ] Don't load package.el at runtime (#43).
    * [x] Support registering a package without installing it (#44).
    * [x] Make sure straight-freeze-versions installs registration-only packages before freezing.
    * [ ] Figure out why ESS wants to make autoloads (#61).
    * [ ] Automatically prune build directory (#50).
    * [ ] Build texinfo manuals (#71).
    * [ ] Support other build commands (#72).
* [ ] Make version-control support more customizable.
    * [x] Support upstream/fork workflow (#29).
    * [x] Remove pbl (#25).
        * [x] Fix superfluous symlinking (#63).
    * [x] Support pluggable version-control backends.
    * [x] Install versions specified in lockfile by default (#23).
        * [x] Clone correct version of straight.el on initial setup (#56).
        * [x] Allow to specify a custom recipe for straight.el (#57).
    * [x] Support deferred installation in straight-freeze-versions (#24).
    * [x] Add straight-override-package (#39).
    * [ ] Fix bugs introduced by new version-control support.
        * [x] Fix issues with default-directory in popup system (#53).
        * [ ] Improve UX around pushing (#54).
        * [ ] Show unmerged commits when considering pull or push (#55).
        * [ ] Fetch if needed in straight-thaw-versions (#58).
        * [x] Eliminate nil branch name error (#59).
        * [x] Fix byte-compilation staleness (#60).
        * [x] Remove option to set remote URLs (#64).
        * [ ] Set pushRemote and/or pushDefault when validating remotes (#65).
        * [ ] Move away from decapitation (#66).
* [x] Support pluggable recipe repositories (#30).
    * [x] Support org-elpa (#36).
    * [x] Support elpa externals-list (#18).
    * [x] Figure out why profile-dotemacs doesn't show up in Emacsattic (#52).
    * [x] Save versions of recipe repositories in lockfile (#26).
    * [ ] Use heuristics from borg.el to compute EmacsMirror recipes (#40).
    * [x] Prefix argument should make straight-get-recipe prompt for recipe source (#62).
* [ ] Improve performance (#9):
    * [ ] Add option to only rebuild packages when changed in Emacs (#41).
* [ ] Improve use-package integration:
    * [x] Make use-package-install-deferred-package work (upstream, see jwiegley/use-package#479).
    * [ ] Integrate registration-only package usage with use-package (#45).
* [x] Miscellaneous tasks:
    * [x] Don't expose the internal arguments of straight-use-package (#46).
    * [x] Add Travis to check byte-compilation (#19).
        * [x] Run checkdoc on Travis (#75).
        * [x] Check for long lines on Travis (#77).
    * [ ] Allow overriding a package's commit hash in your own lockfile (#67).
    * [x] Neuter package.el (#73).
* [ ] Add comprehensive documentation (#28, #51).
    * [ ] Add example configurations (#74).

**Comment by raxod502** [comment]
### New recipe specification

* `:name` - name of package, as a string
* `:local-repo` - name of local repository, as a string; defaults to a
  value possibly provided by the VC backend, or the name of the
  package
* `:type` - VC backend, as a symbol; support for git is built-in
    * `:host` - symbol specifying interpretation of `:repo`, can be
      nil (for url), github, gitlab, or bitbucket; defaults to nil
    * `:repo` - url or shorthand
    * `:branch` - branch to use for primary development; defaults to
      master
    * `:remote` - name of remote to use; defaults to origin
    * `:upstream` - optional, specifies upstream repository; plist
      with keys `:host`, `:repo`, `:branch`, `:remote` as under
      `:type`

**Comment by raxod502** [comment]
### Proposal for eliminating build step

Modified and added recipe keys:

* `:load-path` - list of relative paths to be added to load path for
  package and to be used for autoload generation; defaults to root
  directory or `lisp` subdirectory if provided, or is generated based
  on `:files` specification
* `:autoloads-file` - filename for autoloads file, defaults to package
  name
* `:files` - list of files to be considered as part of the package;
  affects autoload generation and dependency resolution

The old workflow went something like the following:

* At straight.el load-time, use find(1) to check for updates to any
  packages in the build cache. If there are none, then checks for
  packages in the build cache can later be skipped, as an
  optimization.
* When a package is registered:
    * Check if its repository is available. If not, and the user
      confirms, clone it.
    * Add its build directory to the load path.
    * Check if the package has been modified since its last build; if
      so:
        * Recursively delete the build directory.
        * Symlink the files specified by `:files` into the build
          directory.
        * Compute the dependencies of the package based on the files
          in the build directory, and store these in the build cache.
        * Register all of the package's dependencies.
        * Generate the autoloads for the package based on the files in
          the build directory.
        * Byte-compile the package's files in the build directory.
    * Register all of the package's dependencies.
    * Activate the package's autoloads.

The new workflow will go something like the following:

* When a package is registered:
    * Check if its repository is available. If not, and the user
      confirms, clone it.
    * Add the repository to the load path, according to `:load-path`.
    * Compute the dependencies, according to `:files`, and store these
      in a cache.
    * Register all of the package's dependencies.
    * Determine the autoloads file, according to `:autoloads-file`. If
      it does not exist, generate it based on `:files` and
      `:load-path`.
    * Activate the package's autoloads.
* To update the dependencies for a package, run `M-x
  straight-update-dependencies`.
* ...

**Comment by raxod502** [comment]
Closing this in favor of https://github.com/raxod502/straight.el/milestone/1. It's too much work to keep up to date.
